# Generated by Django 4.0.5 on 2022-07-24 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_productrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrating',
            name='ProductId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product'),
        ),
        migrations.AddField(
            model_name='productrating',
            name='Rating',
            field=models.IntegerField(default=0),
        ),
    ]
