# Generated by Django 4.0.5 on 2022-07-24 20:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_productrating_productid_productrating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
