# Generated by Django 4.0.5 on 2022-07-25 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrating',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.customer'),
        ),
    ]
