# Generated by Django 4.0.5 on 2022-07-25 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_orderitem_product_alter_productrating_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrating',
            name='User',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.customer'),
        ),
    ]
