# Generated by Django 4.0.5 on 2022-07-25 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_productrating_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrating',
            name='User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.customer'),
        ),
    ]
