# Generated by Django 4.0.5 on 2022-07-25 12:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0014_alter_productrating_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrating',
            name='User',
        ),
        migrations.AddField(
            model_name='productrating',
            name='User',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
