# Generated by Django 4.0.5 on 2022-07-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_remove_productrating_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrating',
            name='user',
            field=models.ManyToManyField(blank=True, to='store.customer'),
        ),
    ]
