# Generated by Django 4.0.5 on 2022-07-30 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_productrating_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrating',
            name='user',
            field=models.ManyToManyField(to='store.customer'),
        ),
    ]
