# Generated by Django 4.0.5 on 2022-07-31 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_productrating_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Stock_status',
            new_name='stock_status',
        ),
    ]
