# Generated by Django 4.0.5 on 2022-07-31 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_rename_stock_status_product_stock_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
    ]
