# Generated by Django 4.0.5 on 2022-08-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_alter_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrating',
            name='comment',
            field=models.TextField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='productrating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
