# Generated by Django 4.0.5 on 2022-08-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_productrating_comment_productrating_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrating',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
