# Generated by Django 4.0.5 on 2022-08-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_alter_productrating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrating',
            name='comment',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
