# Generated by Django 4.0.5 on 2022-08-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_alter_productrating_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrating',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
