# Generated by Django 4.0.5 on 2022-08-10 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_alter_productrating_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrating',
            name='comment',
        ),
    ]
