# Generated by Django 4.0.5 on 2022-08-10 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_remove_productrating_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrating',
            name='created_at',
        ),
    ]
