# Generated by Django 4.0.5 on 2022-08-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_productrating_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
