# Generated by Django 4.0.5 on 2022-08-10 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_productrating_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrating',
            name='comment',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
